#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'opencv-ros2','console_scripts','face_detection'
__requires__ = 'opencv-ros2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('opencv-ros2', 'console_scripts', 'face_detection')()
    )
